<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sofiainstance" nsURI="http://vicci.eu/sofiainstance/1.0" nsPrefix="sofiainstance">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessInstance" eSuperTypes="#//ProcessStepInstance">
    <eOperations name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="parameters">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="#//DataTypeInstance"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessStepInstance" eSuperTypes="#//Stateful #//InstanceIdentifiable">
    <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="stop"/>
    <eOperations name="pause"/>
    <eOperations name="kill"/>
    <eOperations name="deploy">
      <eParameters name="mapper" eType="#//MappingUtil"/>
    </eOperations>
    <eOperations name="configure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="Configuration" eType="#//Configuration"/>
    </eOperations>
    <eOperations name="escalate"/>
    <eOperations name="resume"/>
    <eOperations name="deactivate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processStepType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//ProcessStep"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permission" lowerBound="1"
        eType="#//ExecutionPermission"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1" upperBound="-1"
        eType="#//PortInstance" containment="true" eOpposite="#//PortInstance/processStepInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
        eType="#//ProcessStepInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processInstanceID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processModelID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cyberPhysical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="active"/>
    <eLiterals name="inactive" value="1"/>
    <eLiterals name="executing" value="2"/>
    <eLiterals name="executed" value="3"/>
    <eLiterals name="paused" value="4"/>
    <eLiterals name="stopped" value="5"/>
    <eLiterals name="failed" value="6"/>
    <eLiterals name="killed" value="7"/>
    <eLiterals name="waiting" value="8"/>
    <eLiterals name="undeployed" value="9"/>
    <eLiterals name="escalated" value="10"/>
    <eLiterals name="deactivated" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stateful" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionState" lowerBound="1"
        eType="#//State" volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpsExecutionState" eType="#//CpsState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortInstance" abstract="true" eSuperTypes="#//Stateful #//InstanceIdentifiable #//Nameable">
    <eOperations name="deploy">
      <eParameters name="mapper" eType="#//MappingUtil"/>
    </eOperations>
    <eOperations name="activate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="parameter" eType="#//DataTypeInstance"/>
    </eOperations>
    <eOperations name="deactivate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processStepInstance" eType="#//ProcessStepInstance"
        eOpposite="#//ProcessStepInstance/ports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outTransitionInstances"
        upperBound="-1" eType="#//TransitionInstance" containment="true" eOpposite="#//TransitionInstance/sourcePortInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decoupled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inTransitionInstances"
        eType="#//TransitionInstance" eOpposite="#//TransitionInstance/targetPortInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceIdentifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instancenumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringTypeInstance" eSuperTypes="#//DataTypeInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringTypeType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//StringType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerTypeInstance" eSuperTypes="#//DataTypeInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="integerTypeType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//IntegerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleTypeInstance" eSuperTypes="#//DataTypeInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doubleTypeType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//DoubleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanTypeInstance" eSuperTypes="#//DataTypeInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanTypeType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//BooleanType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionInstance" eSuperTypes="#//InstanceIdentifiable">
    <eOperations name="deploy">
      <eParameters name="mapper" eType="#//MappingUtil"/>
    </eOperations>
    <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="parameter" eType="#//DataTypeInstance"/>
    </eOperations>
    <eOperations name="deactivate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePortInstance" lowerBound="1"
        eType="#//PortInstance" eOpposite="#//PortInstance/outTransitionInstances"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPortInstance" lowerBound="1"
        eType="#//PortInstance" eOpposite="#//PortInstance/inTransitionInstances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPortInstance" abstract="true" eSuperTypes="#//PortInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataInstance" lowerBound="1"
        eType="#//DataTypeInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlPortInstance" abstract="true"
      eSuperTypes="#//PortInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartPortInstance" abstract="true" interface="true">
    <eOperations name="executeSubSteps"/>
    <eOperations name="deactivateSubSteps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndPortInstance" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartControlPortInstance" eSuperTypes="#//ControlPortInstance #//StartPortInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartDataPortInstance" eSuperTypes="#//DataPortInstance #//StartPortInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndControlPortInstance" eSuperTypes="#//ControlPortInstance #//EndPortInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndDataPortInstance" eSuperTypes="#//DataPortInstance #//EndPortInstance"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecutionPermission">
    <eLiterals name="delayed"/>
    <eLiterals name="denied" value="1"/>
    <eLiterals name="granted" value="2"/>
    <eLiterals name="synchronized" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeInstance" eSuperTypes="#//InstanceIdentifiable #//Nameable">
    <eOperations name="parse">
      <eParameters name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="compareTo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="o" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="serializeToXML" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="deserializeFromXML" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="xmlInstance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="copy" lowerBound="1" eType="#//DataTypeInstance"/>
    <eOperations name="serializeToJSON" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="deserializeFromJSON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="jsonString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setValueFromString" lowerBound="1">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getValueAsObject" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypeType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//ComplexTypeInstance"
        eOpposite="#//ComplexTypeInstance/subtypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idOfOrigin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//InstanceIdentifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permission" eType="#//ExecutionPermission"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decoupleNextSteps" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingUtil">
    <eOperations name="mapPort" eType="#//PortInstance">
      <eParameters name="port" eType="ecore:EClass sofia.ecore#//Port"/>
    </eOperations>
    <eOperations name="mapProcessStep" eType="#//ProcessStepInstance">
      <eParameters name="processStep" eType="ecore:EClass sofia.ecore#//ProcessStep"/>
    </eOperations>
    <eOperations name="mapTransition" eType="#//TransitionInstance">
      <eParameters name="transition" eType="ecore:EClass sofia.ecore#//Transition"/>
    </eOperations>
    <eOperations name="addProcessStepInstance">
      <eParameters name="instance" eType="#//ProcessStepInstance"/>
    </eOperations>
    <eOperations name="mapDataType" lowerBound="1" eType="#//DataTypeInstance">
      <eParameters name="dataType" eType="ecore:EClass sofia.ecore#//DataType"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionInstance" lowerBound="1"
        eType="#//ConditionInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionInstance">
    <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionInstance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftSide" eType="#//StartDataPortInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightSide" eType="#//StartDataPortInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueTransitionInstance" eSuperTypes="#//TransitionInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseTransitionInstance" eSuperTypes="#//TransitionInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexTypeInstance" eSuperTypes="#//DataTypeInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtypes" lowerBound="1"
        upperBound="-1" eType="#//DataTypeInstance" containment="true" eOpposite="#//DataTypeInstance/belongsTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListTypeInstance" eSuperTypes="#//CollectionTypeInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeInstance" eSuperTypes="#//ComplexTypeInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionItemType" lowerBound="1"
        eType="ecore:EClass sofia.ecore#//DataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetTypeInstance" eSuperTypes="#//CollectionTypeInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EscalationPortInstance" eSuperTypes="#//EndControlPortInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="escalationReason" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopConditionInstance"
        lowerBound="1" eType="#//ConditionInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portsCopyToStartport" upperBound="-1"
        eType="#//EndDataPortToStartDataPortMapInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoopInstance" abstract="true" interface="true"
      eSuperTypes="#//LoopInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopStepWidth" eType="#//StartDataPortInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="ROSInvokeInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessSlotInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataDuplicationStepInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="RESTInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="OSGiInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="SOAPInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumanTaskInstance" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadClassStepInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="SeMiWaInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="TriggeredEventInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="XMLRPCInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="SeMiWaRequestInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataMappingStepInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhileLoopInstance" abstract="true" interface="true"
      eSuperTypes="#//LoopInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndDataPortToStartDataPortMapInstance"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//StartDataPortInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//EndDataPortInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticSelectInvokeInstance"
      abstract="true" interface="true" eSuperTypes="#//OpenHabSemanticInvokeInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticAskInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//OpenHabSemanticInvokeInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticCommandInvokeInstance"
      abstract="true" interface="true" eSuperTypes="#//OpenHabSemanticInvokeInstance"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CpsState">
    <eLiterals name="finished"/>
    <eLiterals name="satisfied"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapeKInstance" abstract="true" interface="true"
      eSuperTypes="#//ProcessStepInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalInvokeInstance" abstract="true"
      interface="true" eSuperTypes="#//ProcessStepInstance"/>
</ecore:EPackage>
