<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sofia" nsURI="http://vicci.eu/sofia/1.0" nsPrefix="sofia">
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Identifiable #//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" lowerBound="1"
        eType="#//Port" eOpposite="#//Port/outTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" lowerBound="1"
        eType="#//Port" eOpposite="#//Port/inTransitions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifCondition" lowerBound="1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invoke" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//CompositeStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypeDefinitions" upperBound="-1"
        eType="#//DataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//Identifiable #//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outTransitions" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/sourcePort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processStep" eType="#//ProcessStep"
        eOpposite="#//ProcessStep/ports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inTransitions" eType="#//Transition"
        eOpposite="#//Transition/targetPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPort" abstract="true" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portDatatype" lowerBound="1"
        eType="#//DataType" eOpposite="#//DataType/portMembers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//DataMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlPort" abstract="true" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessStep" abstract="true" eSuperTypes="#//Identifiable #//Nameable #//CpsStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentstep" eType="#//CompositeStep"
        eOpposite="#//CompositeStep/subSteps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1" upperBound="-1"
        eType="#//Port" containment="true" eOpposite="#//Port/processStep"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtypes" upperBound="-1"
        eType="#//DataType" containment="true" eOpposite="#//DataType/belongsTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subreferences" upperBound="-1"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Comparator">
    <eLiterals name="GreaterThan"/>
    <eLiterals name="SmallerThan" value="1"/>
    <eLiterals name="GreaterThanOrEqual" value="2"/>
    <eLiterals name="SmallerThanOrEqual" value="3"/>
    <eLiterals name="Equal" value="4"/>
    <eLiterals name="Distinct" value="5"/>
    <eLiterals name="Identic" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparator" lowerBound="1"
        eType="#//Comparator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftSide" eType="#//StartDataPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightSide" eType="#//StartDataPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicStep" abstract="true" eSuperTypes="#//ProcessStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeStep" abstract="true" eSuperTypes="#//ProcessStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
        eType="#//ProcessStep" containment="true" eOpposite="#//ProcessStep/parentstep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//Nameable #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//ComplexType"
        eOpposite="#//ComplexType/subtypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//DataMapping" containment="true" eOpposite="#//DataMapping/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portMembers" upperBound="-1"
        eType="#//DataPort" eOpposite="#//DataPort/portDatatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" abstract="true" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericType" abstract="true" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//NumericType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleType" eSuperTypes="#//NumericType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" abstract="true" eSuperTypes="#//CompositeStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopCondition" lowerBound="1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portsCopyToStartsport"
        upperBound="-1" eType="#//EndDataPortToStartDataPortMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatLoop" eSuperTypes="#//Loop"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhileLoop" eSuperTypes="#//Loop"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//Loop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopStepWidth" eType="#//StartDataPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessSlot" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataMappingStep" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//DataMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartControlPort" eSuperTypes="#//ControlPort #//StartPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndControlPort" eSuperTypes="#//ControlPort #//EndPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartDataPort" eSuperTypes="#//DataPort #//StartPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndDataPort" eSuperTypes="#//DataPort #//EndPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartPort" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndPort" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggeredEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EPLStatement" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueTransition" eSuperTypes="#//Transition"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseTransition" eSuperTypes="#//Transition"/>
  <eClassifiers xsi:type="ecore:EClass" name="SOAPInvoke" eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverUri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlUri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLRPCInvoke" eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverUri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startParameterSequence"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endParameterSequence" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadClassStep" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegateClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeMiWaInvoke" eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTInvoke" eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HTTPMethod" lowerBound="1"
        eType="#//HTTPverb"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServerUri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OSGiInvoke" eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceClassName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterTypes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeMiWaRequest" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SSILStatement" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMapping" eSuperTypes="#//Identifiable #//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//DataType" eOpposite="#//DataType/mappings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataDuplicationStep" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="ROSInvoke" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverUri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EEnum" name="HTTPverb">
    <eLiterals name="PUT"/>
    <eLiterals name="GET" value="1"/>
    <eLiterals name="POST" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionItemType" lowerBound="1"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//CollectionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublishMessage" abstract="true" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublishROSMessage" eSuperTypes="#//PublishMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="HumanTask" eSuperTypes="#//AtomicStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="humanTaskType" lowerBound="1"
        eType="#//HumanTaskType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="humanTaskUseCase" lowerBound="1"
        eType="#//HumanTaskUseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EscalationPort" eSuperTypes="#//EndControlPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="escalationTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndDataPortToStartDataPortMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//EndDataPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//StartDataPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticInvoke" abstract="true"
      eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverBaseAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="withLatest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticSelectInvoke" eSuperTypes="#//OpenHabSemanticInvoke"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticAskInvoke" eSuperTypes="#//OpenHabSemanticInvoke"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHabSemanticCommandInvoke" eSuperTypes="#//OpenHabSemanticInvoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemanticTargetType">
    <eLiterals name="ASK_QUERY"/>
    <eLiterals name="SELECT_QUERY" value="1"/>
    <eLiterals name="POST_COMMAND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CpsStep" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cyberPhysical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eplQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlProcessId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlProcess" eType="#//Process"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapeK" eSuperTypes="#//AtomicStep"/>
  <eClassifiers xsi:type="ecore:EEnum" name="HumanTaskType">
    <eLiterals name="HINT"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="INTERACTION" value="2"/>
    <eLiterals name="ERROR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HumanTaskUseCase">
    <eLiterals name="UNIVERSAL"/>
    <eLiterals name="COFFEE" value="1"/>
    <eLiterals name="HEATING" value="2"/>
    <eLiterals name="ORDER" value="3"/>
    <eLiterals name="PLANTS" value="4"/>
    <eLiterals name="BELL" value="5"/>
    <eLiterals name="HEALTH" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalInvoke" eSuperTypes="#//Invoke">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invokeGoal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quality" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
