language: java
jdk:
  - oraclejdk8
  
script: mvn deploy

deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
    
env:
  global:
    - GH_REF: github.com/IoTUDresden/proteus-repo